### ISSUE TITLE
Mouse double click event stopped working on v1.8.5

### ISSUE THREAD

**Issue by FrozDark** [judero01col/GMap.NET#10]
After updating the GMap from 1.8.1 to 1.8.5. the mouse double click event stopped working

**Comment by judero01col** [comment]
Greetings, I just performed the test the double click event is working. Could you give me the information about what you are trying to do?

**Comment by FrozDark** [comment]
I have a usercontrol with the map in it. I have set GMapControl modifiers property to public. After creating the usercontrol I create DoubleClick event listener
MapElement.MapControl.MouseDoubleClick += MapControl_MouseDoubleClick;
But the event doesn't fires

**Comment by Chadley08** [comment]
I have also noticed that the double click event has stopped firing in 1.8.5

**Comment by GusGiann** [comment]
Me to on GmapControl in general. OnPolygon and onMarker click works fine.

**Comment by judero01col** [comment]
I found the error, the solution I am going to publish in version 1.8.6, I will try to publish tomorrow in afternoons, greetings.

**Comment by GusGiann** [comment]
Can you please please please give info and directions **what to fix and were** because I have already customized Gmap.net 1.8.5 Core to work with paid Maps (take in mind that I am a VB Developer)
Thank you very much in advance for your help!

**Comment by judero01col** [comment]
Greetings, you should only correct the invasion of the MouseDoubleClick event in the GMapControl class of the GMap.NET.WindowsForms project.

I leave a few screenshots of the change you must make

this is the location
![image](https://user-images.githubusercontent.com/22176530/47940414-80242000-deb8-11e8-84de-b372414e9c2e.png)

method to modify
![image](https://user-images.githubusercontent.com/22176530/47940455-9f22b200-deb8-11e8-936b-3474e549cb77.png)

change made in red
![image](https://user-images.githubusercontent.com/22176530/47940803-e2315500-deb9-11e8-96ee-81cf99f51f8b.png)

**Comment by judero01col** [comment]
Excuse me just out of curiosity, and if you can know, what are the maps you are integrating?

**Comment by GusGiann** [comment]
Very Sorry for the late reply. 
First of all Thank you very much for your images and explanation for the double click(I mentioned I am primarily a VB Developer so it is a painful to search code in C).

We Use Here Maps for Tile Maps,Geocoding and reverse Geocoding because for my country is more complete in street numbers.

**I Know that you have included HereMapsProvider** but as i have already mentioned Here Maps expect different declaration of local language (3 letters country language) for displaying the appropriate tiles (not the default 2 letter country code en,el, etc), and Here Maps Traffic Tiles spend lot of client account credit. So we used different tile set and different language declaration for Geocoding and Reverse Geocoding from HereMaps (and not nominatim from OpenStreetMaps) I used StreamReaders on Rest Api (because I don't like Java and JS either) to get the job done.

Till today seems to work just fine hopping not to overpass the financial budget of client.

If you have any other questions i will be more than happy to help you also.!

Cheers !!
