### ISSUE TITLE
Exception thrown: 'System.EntryPointNotFoundException' in GMap.NET.Core.dll

### ISSUE THREAD

**Issue by g0d** [judero01col/GMap.NET#166]
No matter what version of Windows, .NET framework or VS, no mater the CPU architecture, it always crashes leaving the whole library useless.

**Comment by zgabi** [comment]
Why do you need an entry point? This is a class library, it has no entry point.
We are using this library in our product with VS 2022 / .NET 6 on the latest Windows 10 and Windows server 2022 withoiut any problem. We are also using an older version of this libraray with VS 2019 /  .NET 5 on Windows 10... also no problem.

**Comment by g0d** [comment]
I didn't do anything.... This error happens during compilation time in VS

**Comment by zgabi** [comment]
The screenshot is not from compile time...

**Comment by zgabi** [comment]
The problem is on your side. It definitly works:

Small test app:
![image](https://user-images.githubusercontent.com/3104253/185603778-5be8f8c0-35e0-4a83-a74b-39be88365e79.png)

When I execure it:
![image](https://user-images.githubusercontent.com/3104253/185603873-0f314f9e-2476-4117-b118-567dae660632.png)

**Comment by g0d** [comment]
I will investigate further...
