### ISSUE TITLE
use offline map

### ISSUE THREAD

**Issue by MohammadMokhalled** [judero01col/GMap.NET#18]
hello
how can I use offline map? for example google map

**Comment by GusGiann** [comment]
> 
> 
> hello
> how can I use offline map? for example google map

for using offline map you must take advantage of GmapControl.CacheLocation. But in version 1.8.5 there is a problem. Please Read this ; https://github.com/judero01col/GMap.NET/issues/19#issue-370508479

**Comment by MohammadMokhalled** [comment]
is there any way to download map cache and place it in a folder? i mean without looking everywhere n map to download it.

**Comment by GusGiann** [comment]
Have in mind that many MapProviders have strict policy in Tile and Geocoding Traffic. Having that in mind and monitoring that traffic for not exceeding it, I always let users to create the cache.. It's easier this way because sometimes it gets realy HUGE.(200 sq Km created a 8GB cache in total.) A workaround is to create a box with UpperLeft,UpperRight,DownLeft,DownRight coordinates prior of using that cache in your application and cache with a  secondary app that you will write, calling coordinatres from inside the box mentioned above in all zoom levels you want (ex. 18>=zoom>=10).
Then Take Cache Database and use it as you like.
I dont use Demos that come with Gmap.Net because i cant't take the map tiles in my language !
Searched in manual for other solution once but i havent found any manual, so I cocluded in my own workaround for that.

Hope I Helped.

**Comment by MohammadMokhalled** [comment]
that's good idea. 
I didn't find any manual like you, that's why I asked it here.
this idea you say works but I was looking for easier way for a lazy guy like me :)
I'll use your advise for my program cache.

thanks

**Comment by judero01col** [comment]
If what you want is to share the cache with multiple users, I recommend you better use of secondary cache database with sql server, you can do it in the following way.


MsSQLPureImageCache ch = new MsSQLPureImageCache ();
                 ch.ConnectionString = @ "data source = (local); User Id = DB_A3B2C9_GMapNET_admin; initial catalog = DB_A3B2C9_GMapNET; password = User @ 2018;";
                 MainMap.Manager.SecondaryCache = ch;

**Comment by MohammadMokhalled** [comment]
thanks
I will test it

**Comment by Yogesh12326** [comment]
How we can use map using Gmap.Net GmapConrol in offline mode with all area?

I want to use CacheOnly access mode.

 Is there any way to use this control offline or any Cache management technique?

**Comment by GusGiann** [comment]
The only easy way is to let application buildup cache of tile maps and then set it to use only cache with your map provider.
Beware that if cache is not renew in regular basis you will end up to have old map tiles that will not represent actual imagery.

**Comment by GusGiann** [comment]
> How we can use map using Gmap.Net GmapConrol in offline mode with all area?
> 
> I want to use CacheOnly access mode.
> 
> Is there any way to use this control offline or any Cache management technique?

The only easy way is to let application buildup cache of tile maps and then set it to use only cache with your map provider.
Beware that if cache is not renew in regular basis you will end up to have old map tiles that will not represent actual imagery.
