### ISSUE TITLE
Caching Maps on NetWork Location Doesn't Work For All Map Providers.

### ISSUE THREAD

**Issue by GusGiann** [judero01col/GMap.NET#19]
When a Network Location  ( example \\\SERVER_C\Maps\ ) is specified as a CacheLocation for GmapControl  GMDB, database is not created from the start and afterwards even if you copy database to its place, its not being accessed by the control for storing MapTile References. (Have in mind that Network folder sharing options are loose.)

As a Result centrilized cache not working and so traffic and cache builds up when multiple users access the map.
If CacheLocation is specified in local pc_client drive, CacheLocation Works FINE.!!!?
Any Ideas?
Please Help !

**Comment by judero01col** [comment]
This may be due to the permissions of your application, you can try running your application as administrator.

If what you want is to share the cache with multiple users, I recommend you better use of secondary cache database with sql server, you can do it in the following way.


MsSQLPureImageCache ch = new MsSQLPureImageCache ();
ch.ConnectionString = @ "data source = (local); User Id = DB_A3B2C9_GMapNET_admin; initial catalog = DB_A3B2C9_GMapNET; password = User @ 2018;";
MainMap.Manager.SecondaryCache = ch;

**Comment by GusGiann** [comment]
Thank you for your guidence.! I will give it a try !
